BoxLayout:
    orientation: "vertical"
    show_pic: None
    BoxLayout:
        canvas:
            Rectangle:
                texture: root.show_pic
                pos: self.pos
                size: self.size
                #pos_hint: {'center_x': .5, 'center_y': .5}
                #color: 0, 0, 0, 1
    BoxLayout:
        orientation: "vertical"
        BoxLayout
            MDRaisedButton:
                id: button_load
                text: 'F'
                font_size: 30
                font_name: './font/heydings-icons-1'
                width: root.width * 0.5
                line_color: 1, 1, 1, 1
